# coding: utf-8

"""
    Uber API

    Move your app forward with the Uber API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_list import ProductList  # noqa: E501
from swagger_client.rest import ApiException


class TestProductList(unittest.TestCase):
    """ProductList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductList(self):
        """Test ProductList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_list.ProductList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
