# coding: utf-8

"""
    Uber API

    Move your app forward with the Uber API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products_get(self):
        """Test case for products_get

        Product Types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
