# coding: utf-8

"""
    Uber API

    Move your app forward with the Uber API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.estimates_api import EstimatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEstimatesApi(unittest.TestCase):
    """EstimatesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.estimates_api.EstimatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_estimates_price_get(self):
        """Test case for estimates_price_get

        Price Estimates  # noqa: E501
        """
        pass

    def test_estimates_time_get(self):
        """Test case for estimates_time_get

        Time Estimates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
