# coding: utf-8

"""
    Uber API

    Move your app forward with the Uber API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Profile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'picture': 'str',
        'promo_code': 'str'
    }

    attribute_map = {
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'picture': 'picture',
        'promo_code': 'promo_code'
    }

    def __init__(self, first_name=None, last_name=None, email=None, picture=None, promo_code=None):  # noqa: E501
        """Profile - a model defined in Swagger"""  # noqa: E501

        self._first_name = None
        self._last_name = None
        self._email = None
        self._picture = None
        self._promo_code = None
        self.discriminator = None

        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if picture is not None:
            self.picture = picture
        if promo_code is not None:
            self.promo_code = promo_code

    @property
    def first_name(self):
        """Gets the first_name of this Profile.  # noqa: E501

        First name of the Uber user.  # noqa: E501

        :return: The first_name of this Profile.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Profile.

        First name of the Uber user.  # noqa: E501

        :param first_name: The first_name of this Profile.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Profile.  # noqa: E501

        Last name of the Uber user.  # noqa: E501

        :return: The last_name of this Profile.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Profile.

        Last name of the Uber user.  # noqa: E501

        :param last_name: The last_name of this Profile.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this Profile.  # noqa: E501

        Email address of the Uber user  # noqa: E501

        :return: The email of this Profile.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Profile.

        Email address of the Uber user  # noqa: E501

        :param email: The email of this Profile.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def picture(self):
        """Gets the picture of this Profile.  # noqa: E501

        Image URL of the Uber user.  # noqa: E501

        :return: The picture of this Profile.  # noqa: E501
        :rtype: str
        """
        return self._picture

    @picture.setter
    def picture(self, picture):
        """Sets the picture of this Profile.

        Image URL of the Uber user.  # noqa: E501

        :param picture: The picture of this Profile.  # noqa: E501
        :type: str
        """

        self._picture = picture

    @property
    def promo_code(self):
        """Gets the promo_code of this Profile.  # noqa: E501

        Promo code of the Uber user.  # noqa: E501

        :return: The promo_code of this Profile.  # noqa: E501
        :rtype: str
        """
        return self._promo_code

    @promo_code.setter
    def promo_code(self, promo_code):
        """Sets the promo_code of this Profile.

        Promo code of the Uber user.  # noqa: E501

        :param promo_code: The promo_code of this Profile.  # noqa: E501
        :type: str
        """

        self._promo_code = promo_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Profile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
